### ISSUE TITLE
New default densities

### ISSUE THREAD

**Issue by equinusocio** [limitlessloop/postcss-help-media-queries#3]
These are the new default densities:

```js
densities: {
	'1x': '160dpi',
	'1.5x': '240dpi',
	'2x': '320dpi',
	'3x': '480dpi',
	'4x': '640dpi'
},
``` 

Also, densities and orientations should not be inside the configuration, they are "standard" values related to the device.

**Comment by gavinmcfarland** [comment]
No problem. It should be relatively easy to make it so you can only change the breakpoints. It just allowed all because it was the simplest option. I can fix that.
